OPSEXP-1549: add tomcat10 images
Alfresco/alfresco-docker-base-tomcat pull request #101
Opened 2023-06-27 06:52 UTC by alxgomz

OPSEXP-1549Ref:

2023-06-27 09:00 UTC, gionn requested changes

2023-06-28 08:52 UTC, alxgomz commented on Dockerfile
> +  #gpg --batch --verify tomcat.tar.gz.asc tomcat.tar.gz && \
totally!

2023-06-28 08:57 UTC, gionn requested changes

2023-06-28 08:57 UTC, gionn commented on updatecli.d/01_tomcat_version.tpl
> +      branch: "main"
```suggestion
      url: https://github.com/apache/tomcat.git
      branch: main
```

consistency

2023-06-28 08:57 UTC, gionn commented on updatecli.d/01_tomcat_version.tpl
>        key: tomcat_version
```suggestion
      key: tcnative_version
```

2023-06-28 08:57 UTC, gionn commented on updatecli.d/02_tomcat_checksum.tpl
> +    name: Retrieve the tomcat native libs  checksum
```suggestion
    name: Retrieve the tomcat native libs checksum
```

2023-06-28 09:27 UTC, gionn approved these changes

2023-06-28 10:43 UTC, merged