OPSEXP-2240 Provide a rockylinux 9 + tomcat 10 tomcat base image
Alfresco/alfresco-docker-base-tomcat pull request #109
Opened 2023-09-20 16:12 UTC by slohe1

OPSEXP-2240

2023-09-21 07:35 UTC, gionn reviewed
there are a bunch of dependabots open on this repo, merge them and verify as part of this jira

2023-09-21 07:35 UTC, gionn commented on .github/workflows/main.yml
> -          - jdk
remove jdist from here and dockerfile if we don't need it anymore

2023-09-21 07:54 UTC, alxgomz requested changes
We should not produce this one as tomcat 10 is only supported starting with 23.1 and centos 7 is not anymore on the supported stack for 23.1.
the only centos7 based image we need is tomcat9 + jre 11

2023-09-21 10:34 UTC, gionn commented on .github/workflows/main.yml
> +            java_major: 11
at this point it's more concise if we just use `include`

2023-09-22 07:10 UTC, gionn approved these changes

2023-09-22 08:22 UTC, alxgomz approved these changes

2023-09-22 08:45 UTC, merged